RULES = {
    "SECRET001": ("BLOCKER", "OpenAI-compatible secret key committed."),
    "SECRET002": ("BLOCKER", "GitHub token committed."),
    "SECRET003": ("BLOCKER", "AWS access key committed."),
    "SECRET004": ("BLOCKER", "Stripe live secret committed."),
    "SECRET005": ("BLOCKER", "Telegram bot token committed."),
    "SECRET006": ("BLOCKER", "Private key committed."),
    "ENV001": ("BLOCKER", "Real .env-style file is present in the scanned project."),
    "ENV002": ("BLOCKER", "Secret-looking frontend environment variable is public."),
    "MIG001": ("BLOCKER", "Destructive SQL migration requires explicit production review."),
    "GIT001": ("HIGH", "No .gitignore detected."),
    "GIT002": ("HIGH", ".env files are not ignored."),
    "DEP001": ("HIGH", "Dependency manifest exists without a lock file."),
    "RECOVERY001": ("HIGH", "Migrations lack documented backup and rollback."),
    "RUNTIME001": ("HIGH", "Debug mode appears enabled."),
    "SEC001": ("HIGH", "Wildcard CORS configuration detected."),
    "TEST001": ("MEDIUM", "No automated tests detected."),
    "CI001": ("MEDIUM", "No CI workflow detected."),
    "AUTH001": ("MEDIUM", "Admin-looking route lacks obvious authorization markers."),
}
